repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
        args: ["--maxkb=5120"]
      - id: check-docstring-first
      - id: check-toml
      - id: debug-statements
      - id: detect-private-key
      - id: requirements-txt-fixer
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.4
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: "v8.56.0"
    hooks:
      - id: eslint
        files: \.[jt]sx?$ # *.js, *.jsx, *.ts and *.tsx
        types: [file]
        args: [--fix, --config, frontend/.eslintrc.js]
        additional_dependencies:
          - eslint-loader@1.6.1
          - eslint@4.15.0
          - eslint-plugin-react@6.10.3
          - babel-eslint@6.1.2
          - eslint-plugin-unused-imports@2.0.0
          - eslint-plugin-simple-import-sort@9.0.0
          - eslint-plugin-prettier@4.2.1
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.7.1"
    hooks:
      - id: prettier
        types_or: [css, javascript, ts, tsx]
