services:
  reverse_proxy:
    image: nginx_frontend
    hostname: reverse_proxy
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    restart: on-failure
    depends_on:
      - backend

  backend:
    image: word_chain_game
    hostname: backend
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    # ports: # API is available only inside the network, do not expose it's port
    env_file:
      - deployment/.env.backend
    restart: on-failure
    depends_on:
      - db

  db:
    image: postgres:14
    # ports: # DB is available only inside the network, do not expose it's port
    env_file:
      - deployment/.env.postgres
    restart: on-failure
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
